import "./ecoprint_logo.jpg";
import "./uploads/8.jpg";
import "./icons/favicon.png";
import "./icons/logo-renius-dark.png";
import "./icons/logo-renius-white.png";
import "./tipos productos/bolsos.jpg";
import "./tipos productos/estuches.jpg";
import "./tipos productos/faldas.jpg";
import "./tipos productos/jeans.jpg";
import "./tipos productos/poleras.jpg";
import "./tipos productos/shorts.jpg";
import "./tipos productos/tops.jpg";